'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { portalApi } from '@/lib/portalApi';

export default function BookingsPage(){
 const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{portalApi.listMyBookings().then(setItems).catch((e:any)=>setError(e.message||'Unable to load bookings')).finally(()=>setLoading(false))},[]);
 return <div className="max-w-[1000px] mx-auto"><div className="mb-7"><p className="text-[11px] font-bold tracking-[3px] uppercase text-[#146BFF]">Bookings</p><h1 className="text-[28px] font-extrabold tracking-tight mt-1">My Vehicle Bookings</h1><p className="text-[13px] text-[#8894A5] mt-1">Your confirmed booking details, always linked to the vehicle enquiry.</p></div>{loading?<div className="bg-white border rounded-2xl p-6">Loading bookings…</div>:error?<div className="bg-red-50 border border-red-200 text-red-700 rounded-2xl p-5 text-sm">{error}</div>:items.length===0?<div className="bg-white border rounded-2xl p-7 text-sm text-[#68758A]">No vehicle booking found yet.</div>:<div className="space-y-3">{items.map(b=><Link key={b.id} href={`/portal/leads/${b.leadId}`} className="block bg-white border border-[#E3E8EF] rounded-2xl p-5 hover:border-[#146BFF]/40"><div className="flex justify-between gap-4"><div><h2 className="font-extrabold">{b.lead?.brand?.name} {b.lead?.model?.name}</h2><p className="text-xs text-[#8894A5] mt-1">{b.lead?.variant?.name||'Variant not specified'} · {b.lead?.leadCode}</p></div><span className="text-xs font-bold px-3 py-1 rounded-full bg-[#F0F6FF] text-[#146BFF]">Booked</span></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mt-5 text-sm"><div><p className="text-[10px] uppercase text-[#94A0AF]">Booking Amount</p><p className="font-bold mt-1">₹{Number(b.bookingAmount||0).toLocaleString('en-IN')}</p></div><div><p className="text-[10px] uppercase text-[#94A0AF]">Booked On</p><p className="font-bold mt-1">{b.bookedAt?new Date(b.bookedAt).toLocaleDateString('en-IN'):'—'}</p></div><div><p className="text-[10px] uppercase text-[#94A0AF]">Vehicle</p><p className="font-bold mt-1">{b.lead?.variant?.name||b.lead?.model?.name||'—'}</p></div></div></Link>)}</div>}</div>
}
