'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { api } from '@/lib/api';

const SALES_PIPELINE = ['NEW','CONTACTED','QUALIFIED','INTERESTED','TEST_DRIVE','QUOTATION','NEGOTIATION','BOOKING','DELIVERY','CLOSED'];
const STAGE_LABEL: Record<string,string> = {NEW:'Enquiry Received',CONTACTED:'Contacted',QUALIFIED:'Qualified',INTERESTED:'Interested',TEST_DRIVE:'Test Drive',QUOTATION:'Quotation',NEGOTIATION:'Negotiation',BOOKING:'Booked',DELIVERY:'Delivery',CLOSED:'Delivered'};
const money=(n?:number)=>n?`₹${Number(n).toLocaleString('en-IN')}`:'—';
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="bg-white border border-[#E3E8EF] rounded-2xl p-5 mb-5"><h3 className="text-[11px] font-bold uppercase tracking-[2px] text-[#8894A5] mb-4">{title}</h3>{children}</section>}

export default function PortalLeadDetail(){
 const {id}=useParams<{id:string}>(); const [lead,setLead]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [body,setBody]=useState(''); const [sending,setSending]=useState(false);
 async function load(){setLoading(true);try{setLead(await api.getMyLead(id));}catch(e:any){setError(e.message||'Unable to load enquiry.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[id]);
 async function send(e:React.FormEvent){e.preventDefault();if(!body.trim())return;setSending(true);try{await api.sendMyMessage(id,body.trim());setBody('');await load();}catch(e:any){setError(e.message||'Unable to send message.');}finally{setSending(false);}}
 if(loading)return <div className="space-y-4">{[1,2,3].map(i=><div key={i} className="h-32 rounded-2xl bg-white border border-[#E3E8EF] animate-pulse"/>)}</div>;
 if(error||!lead)return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error||'Enquiry not found.'}</div>;
 const idx=SALES_PIPELINE.indexOf(lead.salesStatus); const docs=lead.documents||[]; const finance=lead.financeCase;
 return <div className="max-w-[1000px] mx-auto">
  <div className="mb-5"><Link href="/portal/enquiries" className="text-[12px] text-[#146BFF]">← My Enquiries</Link><p className="text-[10px] font-bold uppercase tracking-[2px] text-[#146BFF] mt-4">{lead.leadCode}</p><h1 className="text-[28px] sm:text-[34px] font-extrabold tracking-tight mt-1">{lead.brand?.name} {lead.model?.name}</h1><p className="text-[13px] text-[#8894A5] mt-1">{lead.variant?.name||'Variant not specified'}</p></div>
  <section className="rounded-2xl bg-[#0D1B35] text-white p-5 sm:p-6 mb-6 overflow-x-auto"><p className="text-[11px] uppercase tracking-[2px] text-[#72B8FF] font-bold">Your vehicle journey</p><div className="flex items-start mt-5 min-w-[720px]">{SALES_PIPELINE.map((s,i)=>{const done=idx>=0&&i<=idx;return <div key={s} className="flex items-start shrink-0"><div className="flex flex-col items-center w-[68px]"><div className={`w-8 h-8 rounded-full flex items-center justify-center text-[10px] font-bold border ${done?'bg-[#146BFF] border-[#72B8FF]':'bg-white/5 border-white/15 text-white/35'}`}>{done?'✓':i+1}</div><span className="text-[9px] text-center mt-2 text-white/65 leading-tight">{STAGE_LABEL[s]}</span></div>{i<SALES_PIPELINE.length-1&&<div className={`w-5 h-px mt-4 ${done&&i<idx?'bg-[#146BFF]':'bg-white/10'}`}/>}</div>})}</div></section>
  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5"><Link href="#finance" className="bg-white border border-[#E3E8EF] rounded-xl p-4"><p className="text-[10px] uppercase text-[#94A0AF]">Finance</p><p className="font-bold text-[14px] mt-1">{finance?STAGE_LABEL[finance.stage]||finance.stage:'Not started'}</p></Link><Link href="#documents" className="bg-white border border-[#E3E8EF] rounded-xl p-4"><p className="text-[10px] uppercase text-[#94A0AF]">Documents</p><p className="font-bold text-[14px] mt-1">{docs.length?`${docs.filter((d:any)=>d.status==='VERIFIED').length}/${docs.length} verified`:'Not requested'}</p></Link><Link href="#booking" className="bg-white border border-[#E3E8EF] rounded-xl p-4"><p className="text-[10px] uppercase text-[#94A0AF]">Booking</p><p className="font-bold text-[14px] mt-1">{lead.booking?'Confirmed':'Pending'}</p></Link><Link href="#delivery" className="bg-white border border-[#E3E8EF] rounded-xl p-4"><p className="text-[10px] uppercase text-[#94A0AF]">Delivery</p><p className="font-bold text-[14px] mt-1">{lead.delivery?.status||'Pending'}</p></Link></div>
  <Section title="Vehicle & Enquiry"><div className="grid sm:grid-cols-3 gap-4 text-[13px]"><div><p className="text-[#94A0AF]">Vehicle</p><p className="font-semibold mt-1">{lead.brand?.name} {lead.model?.name}</p></div><div><p className="text-[#94A0AF]">Variant</p><p className="font-semibold mt-1">{lead.variant?.name||'—'}</p></div><div><p className="text-[#94A0AF]">Current Status</p><p className="font-semibold mt-1">{STAGE_LABEL[lead.salesStatus]||lead.salesStatus}</p></div></div></Section>
  {finance&&<div id="finance"><Section title="Finance"><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-[13px]"><div><p className="text-[#94A0AF]">Loan Amount</p><p className="font-semibold mt-1">{money(finance.loanAmount)}</p></div><div><p className="text-[#94A0AF]">EMI</p><p className="font-semibold mt-1">{money(finance.emi)} / month</p></div><div><p className="text-[#94A0AF]">Tenure</p><p className="font-semibold mt-1">{finance.tenureMonths||finance.tenure||'—'} months</p></div><div><p className="text-[#94A0AF]">Stage</p><p className="font-semibold mt-1">{finance.stage||'—'}</p></div></div><Link href="/portal/finance" className="inline-flex mt-5 text-[12px] font-semibold text-[#146BFF]">Open all finance applications →</Link></Section></div>}
  <div id="documents"><Section title="Documents"><div className="space-y-2">{docs.length?docs.map((d:any)=><div key={d.id} className="flex items-center justify-between gap-3 border border-[#EEF1F5] rounded-xl px-3.5 py-3"><div><p className="text-[13px] font-semibold">{d.type||d.name||'Document'}</p>{d.status==='REJECTED'&&d.rejectionReason&&<p className="text-[11px] text-red-600 mt-1">{d.rejectionReason}</p>}</div><span className="text-[10px] font-semibold px-2.5 py-1 rounded-full bg-[#F5F7FA]">{d.status||'Pending'}</span></div>):<p className="text-[12px] text-[#8894A5]">No documents requested yet.</p>}</div><Link href="/portal/documents" className="inline-flex mt-4 text-[12px] font-semibold text-[#146BFF]">Open document centre →</Link></Section></div>
  <div id="booking"><Section title="Booking & Delivery"><div className="grid sm:grid-cols-2 gap-4 text-[13px]" id="delivery"><div><p className="text-[#94A0AF]">Booking</p><p className="font-semibold mt-1">{lead.booking?'Confirmed':'Not booked yet'}</p>{lead.booking&&<p className="text-[11px] text-[#8894A5] mt-1">Amount: {money(lead.booking.bookingAmount)}</p>}</div><div><p className="text-[#94A0AF]">Delivery</p><p className="font-semibold mt-1">{lead.delivery?.status||'Pending'}</p>{lead.delivery?.scheduledAt&&<p className="text-[11px] text-[#8894A5] mt-1">Scheduled: {new Date(lead.delivery.scheduledAt).toLocaleDateString('en-IN')}</p>}</div></div></Section></div>
  {lead.dealer&&<Section title="Your Dealer"><p className="text-[13px] font-semibold">{lead.dealer.name}</p><p className="text-[12px] text-[#8894A5] mt-1">{[lead.dealer.address,lead.dealer.city].filter(Boolean).join(', ')}</p>{lead.dealer.phone&&<a href={`tel:${lead.dealer.phone}`} className="inline-flex mt-2 text-[12px] text-[#146BFF]">📞 {lead.dealer.phone}</a>}</Section>}
  <Section title="Messages"><div className="space-y-3 mb-4 max-h-72 overflow-y-auto">{lead.messages?.length?lead.messages.map((m:any)=><div key={m.id} className={`flex ${m.senderCustomerId?'justify-end':'justify-start'}`}><div className={`max-w-[80%] rounded-xl px-3 py-2 text-[12.5px] ${m.senderCustomerId?'bg-[#146BFF] text-white':'bg-[#F5F7FA] text-[#374357]'}`}><p>{m.body}</p><p className="text-[9px] opacity-60 mt-1">{m.sender?.name||'MK Finance'} · {new Date(m.createdAt).toLocaleString('en-IN')}</p></div></div>):<p className="text-[12px] text-[#8894A5]">No messages yet.</p>}</div><form onSubmit={send} className="flex gap-2"><input value={body} onChange={e=>setBody(e.target.value)} placeholder="Type a message…" className="flex-1 rounded-xl border border-[#E3E8EF] bg-[#F8FAFC] px-3.5 py-2.5 text-sm outline-none focus:ring-2 focus:ring-[#146BFF]/30"/><button disabled={sending} className="rounded-xl bg-[#146BFF] text-white px-5 text-sm font-semibold disabled:opacity-60">{sending?'Sending…':'Send'}</button></form></Section>
 </div>
}
