'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';

const STAGE: Record<string,string> = { NEW:'Application Started', DOCUMENTS:'Documents', SUBMITTED:'Submitted to Bank', LOGIN:'Bank Login', APPROVED:'Approved', DISBURSED:'Disbursed', REJECTED:'Rejected', HOLD:'On Hold' };
function money(v:any){ return v == null || v === '' ? '—' : '₹' + Number(v).toLocaleString('en-IN'); }
function vehicle(l:any){ return `${l.brand?.name || ''} ${l.model?.name || ''}`.trim() || 'Vehicle'; }

export default function FinancePage(){
 const [leads,setLeads]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{ api.listMyLeads().then(setLeads).catch((e:any)=>setError(e.message || 'Unable to load finance details.')).finally(()=>setLoading(false)); },[]);
 const financeLeads=leads.filter(l=>l.financeRequired || l.financeCase);
 if(loading) return <div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-36 bg-white border border-[#E3E8EF] rounded-2xl animate-pulse"/>)}</div>;
 return <div className="max-w-[1000px] mx-auto"><div className="mb-7"><p className="text-[11px] font-bold tracking-[3px] uppercase text-[#146BFF]">Vehicle Finance</p><h1 className="text-[28px] font-extrabold mt-1">My Finance</h1><p className="text-[13px] text-[#8894A5] mt-1">Finance status for each vehicle enquiry, including bank, loan amount, EMI and application stage.</p></div>{error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{financeLeads.length===0?<div className="bg-white border border-[#E3E8EF] rounded-2xl p-8 text-center"><p className="text-3xl">💳</p><h2 className="font-bold mt-3">No finance application</h2><p className="text-[13px] text-[#8894A5] mt-1">Finance details will appear here after you request vehicle finance.</p><Link href="/cars" className="inline-flex mt-5 rounded-lg bg-[#146BFF] text-white px-5 py-2.5 text-[12px] font-semibold">Explore Vehicles</Link></div>:<div className="space-y-4">{financeLeads.map(l=>{const f=l.financeCase; return <div key={l.id} className="bg-white border border-[#E3E8EF] rounded-2xl p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-extrabold text-[16px]">{vehicle(l)}</p><p className="text-[11.5px] text-[#8894A5] mt-1">{l.variant?.name || 'Variant not specified'} · {l.leadCode}</p></div><span className="rounded-full bg-[#F0F6FF] text-[#146BFF] px-3 py-1 text-[11px] font-semibold">{STAGE[f?.stage] || f?.stage || l.financeStatus || 'Pending'}</span></div>{f&&<div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-5"><div className="rounded-xl bg-[#F9FAFC] p-3"><p className="text-[9px] uppercase text-[#9FABB8]">Bank</p><p className="text-[12px] font-semibold mt-1">{f.bank?.name || 'Assigned by MK Finance'}</p></div><div className="rounded-xl bg-[#F9FAFC] p-3"><p className="text-[9px] uppercase text-[#9FABB8]">Loan Amount</p><p className="text-[12px] font-semibold mt-1">{money(f.loanAmount)}</p></div><div className="rounded-xl bg-[#F9FAFC] p-3"><p className="text-[9px] uppercase text-[#9FABB8]">EMI</p><p className="text-[12px] font-semibold mt-1">{money(f.emi)} / month</p></div><div className="rounded-xl bg-[#F9FAFC] p-3"><p className="text-[9px] uppercase text-[#9FABB8]">Tenure</p><p className="text-[12px] font-semibold mt-1">{f.tenureMonths ? `${f.tenureMonths} months` : '—'}</p></div></div>}<div className="flex flex-wrap gap-2 mt-4 pt-4 border-t border-[#EEF1F5]"><Link href={`/portal/leads/${l.id}#finance`} className="rounded-lg bg-[#146BFF] text-white px-4 py-2 text-[11.5px] font-semibold">Open Finance Details →</Link><Link href={`/portal/leads/${l.id}`} className="rounded-lg border border-[#E3E8EF] px-4 py-2 text-[11.5px] font-semibold">View Vehicle & Enquiry</Link></div></div>})}</div>}</div>;
}
