export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://mk-crm-backend.onrender.com';

function getToken() {
  if (typeof window === 'undefined') return null;
  if (window.location.pathname.startsWith('/portal')) return localStorage.getItem('mk_portal_token');
  return localStorage.getItem('mk_crm_token');
}

async function apiFetch(path: string, options: RequestInit = {}) {
  const token = getToken();
  const res = await fetch(`${API_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers }, cache: 'no-store' });
  const data = await res.json().catch(() => null);
  if (res.status === 401 && typeof window !== 'undefined') {
    if (window.location.pathname.startsWith('/admin') && window.location.pathname !== '/admin/login') { localStorage.removeItem('mk_crm_token'); localStorage.removeItem('mk_staff_user'); window.location.href = '/admin/login'; }
    else if (window.location.pathname.startsWith('/portal') && window.location.pathname !== '/portal/login') { localStorage.removeItem('mk_portal_token'); localStorage.removeItem('mk_portal_customer'); window.location.href = '/portal/login'; }
  }
  if (!res.ok) throw new Error(data?.message || data?.error || 'Something went wrong.');
  return data;
}

export const api = {
  getFullCatalogue: () => apiFetch('/catalogue/full'), getBrands: () => apiFetch('/catalogue/brands'), createBrand: (data: any) => apiFetch('/catalogue/brands', { method: 'POST', body: JSON.stringify(data) }), updateBrand: (id: string, data: any) => apiFetch(`/catalogue/brands/${id}`, { method: 'PUT', body: JSON.stringify(data) }), deleteBrand: (id: string) => apiFetch(`/catalogue/brands/${id}`, { method: 'DELETE' }), getModels: (brandId?: string) => apiFetch(`/catalogue/models${brandId ? `?brandId=${brandId}` : ''}`), createModel: (data: any) => apiFetch('/catalogue/models', { method: 'POST', body: JSON.stringify(data) }), updateModel: (id: string, data: any) => apiFetch(`/catalogue/models/${id}`, { method: 'PUT', body: JSON.stringify(data) }), deleteModel: (id: string) => apiFetch(`/catalogue/models/${id}`, { method: 'DELETE' }), getVariants: (modelId?: string) => apiFetch(`/catalogue/variants${modelId ? `?modelId=${modelId}` : ''}`), getModelDetail: (brandSlug: string, modelSlug: string) => apiFetch(`/catalogue/model/${brandSlug}/${modelSlug}`), getFilterableFields: () => apiFetch('/field-definitions/filterable'), createVariant: (data: any) => apiFetch('/catalogue/variants', { method: 'POST', body: JSON.stringify(data) }), bulkImportVariants: (modelId: string, rows: { name: string; fuelType: string; transmission: string; exShowroomPrice: number }[]) => apiFetch(`/catalogue/models/${modelId}/variants/bulk-import`, { method: 'POST', body: JSON.stringify({ rows }) }), updateVariant: (id: string, data: any) => apiFetch(`/catalogue/variants/${id}`, { method: 'PUT', body: JSON.stringify(data) }), deleteVariant: (id: string) => apiFetch(`/catalogue/variants/${id}`, { method: 'DELETE' }),
  listFeatures: (includeArchived?: boolean) => apiFetch(`/features${includeArchived ? '?includeArchived=true' : ''}`), createFeature: (data: any) => apiFetch('/features', { method: 'POST', body: JSON.stringify(data) }), updateFeature: (id: string, data: any) => apiFetch(`/features/${id}`, { method: 'PUT', body: JSON.stringify(data) }), deleteFeature: (id: string) => apiFetch(`/features/${id}`, { method: 'DELETE' }), getVariantFeatures: (variantId: string) => apiFetch(`/variants/${variantId}/features`), setVariantFeatures: (variantId: string, items: { featureId: string; applicability: string }[]) => apiFetch(`/variants/${variantId}/features`, { method: 'PUT', body: JSON.stringify({ items }) }),
  getWarrantyByVariant: (variantId: string) => apiFetch(`/variants/${variantId}/warranty`), upsertWarranty: (variantId: string, data: any) => apiFetch(`/variants/${variantId}/warranty`, { method: 'PUT', body: JSON.stringify(data) }),
  createCarDataSubmission: (data: any) => apiFetch('/car-data-submissions', { method: 'POST', body: JSON.stringify(data) }), listMySubmissions: (status?: string) => apiFetch(`/car-data-submissions/mine${status ? `?status=${status}` : ''}`), listAllSubmissions: (status?: string, variantId?: string) => { const q = new URLSearchParams(); if (status) q.set('status', status); if (variantId) q.set('variantId', variantId); const qs = q.toString(); return apiFetch(`/car-data-submissions${qs ? `?${qs}` : ''}`); }, getSubmission: (id: string) => apiFetch(`/car-data-submissions/${id}`), approveSubmission: (id: string, reviewNotes?: string) => apiFetch(`/car-data-submissions/${id}/approve`, { method: 'PUT', body: JSON.stringify({ reviewNotes }) }), rejectSubmission: (id: string, reviewNotes?: string) => apiFetch(`/car-data-submissions/${id}/reject`, { method: 'PUT', body: JSON.stringify({ reviewNotes }) }),
  requestOtp: (mobile: string) => apiFetch('/auth/otp/request', { method: 'POST', body: JSON.stringify({ mobile }) }), verifyOtp: (mobile: string, code: string) => apiFetch('/auth/otp/verify', { method: 'POST', body: JSON.stringify({ mobile, code }) }),
  createLead: (data: any) => apiFetch('/leads', { method: 'POST', body: JSON.stringify(data) }), listMyLeads: () => apiFetch('/leads/my'), getMyLead: (id: string) => apiFetch(`/leads/my/${id}`), sendMyMessage: (id: string, body: string) => apiFetch(`/leads/my/${id}/messages`, { method: 'POST', body: JSON.stringify({ body }) }), listMyDocuments: (leadId?: string) => apiFetch(`/documents/my${leadId ? `?leadId=${encodeURIComponent(leadId)}` : ''}`),
  listLeads: (params?: string) => apiFetch(`/leads${params ? `?${params}` : ''}`), getFollowUpDashboard: (params?: string) => apiFetch(`/leads/follow-ups/dashboard${params ? `?${params}` : ''}`), getSalesReport: (from?: string, to?: string) => apiFetch(`/reports/sales${from || to ? `?from=${from || ''}&to=${to || ''}` : ''}`), getFinanceReport: (from?: string, to?: string) => apiFetch(`/reports/finance${from || to ? `?from=${from || ''}&to=${to || ''}` : ''}`), getDealerPerformanceReport: (from?: string, to?: string) => apiFetch(`/reports/dealer-performance${from || to ? `?from=${from || ''}&to=${to || ''}` : ''}`), getExportUrl: (from?: string, to?: string) => `${API_URL}/reports/export?from=${from || ''}&to=${to || ''}`, getLead: (id: string) => apiFetch(`/leads/${id}`), updateLead: (id: string, data: any) => apiFetch(`/leads/${id}`, { method: 'PUT', body: JSON.stringify(data) }), updateLeadNextAction: (id: string, data: any) => apiFetch(`/leads/${id}/next-action`, { method: 'PUT', body: JSON.stringify(data) }), updateLeadBlocker: (id: string, blocker: string | null, blockerCategory?: string | null) => apiFetch(`/leads/${id}/blocker`, { method: 'PUT', body: JSON.stringify({ blocker, blockerCategory }) }), getSlaConfig: () => apiFetch('/leads/sla-config'),
};
