'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';

export default function PortalDocumentsPage() {
  const [docs, setDocs] = useState<any[]>([]); const [leads, setLeads] = useState<any[]>([]); const [leadId, setLeadId] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load(id = leadId) { setLoading(true); setError(''); try { const [d, l] = await Promise.all([api.listMyDocuments(id || undefined), api.listMyLeads()]); setDocs(d || []); setLeads(l || []); } catch (e: any) { setError(e.message || 'Unable to load documents.'); } finally { setLoading(false); } }
  useEffect(() => { load(''); }, []);
  const vehicleFor = (id: string) => leads.find((l) => l.id === id);
  const status = (s: string) => s === 'VERIFIED' ? 'Verified' : s === 'REJECTED' ? 'Rejected' : s === 'PENDING' ? 'Pending review' : 'Uploaded';
  return <div className="max-w-[1050px] mx-auto"><div className="mb-7"><p className="text-[11px] font-bold tracking-[3px] uppercase text-[#146BFF]">Documents</p><h1 className="text-[28px] font-extrabold tracking-tight mt-1">My Documents</h1><p className="text-[13px] text-[#8894A5] mt-1">Documents shared with MK Finance, organised by your vehicle enquiry.</p></div>
    <div className="bg-white border border-[#E3E8EF] rounded-2xl p-4 mb-5 flex flex-col sm:flex-row sm:items-center gap-3"><label className="text-[12px] font-semibold text-[#68758A]">Vehicle enquiry</label><select value={leadId} onChange={(e) => { setLeadId(e.target.value); load(e.target.value); }} className="flex-1 border border-[#E3E8EF] rounded-lg px-3 py-2.5 text-sm"><option value="">All my enquiries</option>{leads.map((l) => <option key={l.id} value={l.id}>{l.brand?.name} {l.model?.name} · {l.variant?.name || l.leadCode}</option>)}</select></div>
    {error && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading ? <div className="space-y-3">{[1,2,3].map(i => <div key={i} className="h-24 bg-white border border-[#E3E8EF] rounded-2xl animate-pulse" />)}</div> : docs.length ? <div className="space-y-3">{docs.map((d) => { const l = vehicleFor(d.leadId); return <div key={d.id} className="bg-white border border-[#E3E8EF] rounded-2xl p-5"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3"><div><p className="font-extrabold text-[14px]">{String(d.type || 'Document').replaceAll('_',' ')}</p><p className="text-[11px] text-[#8894A5] mt-1">{l ? `${l.brand?.name || ''} ${l.model?.name || ''} · ${l.variant?.name || l.leadCode}` : `Lead ${d.leadId}`}</p></div><span className="rounded-full bg-[#F5F7FA] px-3 py-1 text-[11px] font-semibold">{status(d.status)}</span></div><div className="mt-4 flex flex-wrap items-center gap-4 text-[11px] text-[#8894A5]"><span>Version {d.version || 1}</span><span>Uploaded {d.createdAt ? new Date(d.createdAt).toLocaleDateString('en-IN') : '—'}</span>{d.status === 'REJECTED' && d.rejectionReason && <span className="text-red-600">Reason: {d.rejectionReason}</span>}{d.fileUrl && <a href={d.fileUrl} target="_blank" rel="noreferrer" className="ml-auto text-[#146BFF] font-bold">View document ↗</a>}</div></div>})}</div> : <div className="bg-white border border-[#E3E8EF] rounded-2xl p-8 text-center"><div className="text-3xl mb-3">📄</div><h2 className="font-extrabold">No documents yet</h2><p className="text-[13px] text-[#8894A5] mt-1">When MK Finance requests or uploads documents for one of your enquiries, they will appear here.</p><Link href="/portal/leads" className="inline-flex mt-5 rounded-lg bg-[#146BFF] text-white px-5 py-2.5 text-[12px] font-semibold">View My Enquiries</Link></div>}
  </div>;
}
