'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';

const status: Record<string,string>={PENDING:'Required',UPLOADED:'Under Review',VERIFIED:'Approved',REJECTED:'Re-upload required'};
const tone: Record<string,string>={PENDING:'bg-slate-500/10 text-slate-600',UPLOADED:'bg-amber-500/10 text-amber-700',VERIFIED:'bg-emerald-500/10 text-emerald-700',REJECTED:'bg-red-500/10 text-red-700'};
export default function PortalDocumentsPage(){const[leads,setLeads]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{api.listMyLeads().then(setLeads).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);const rows=useMemo(()=>leads.flatMap(l=>(l.documents||[]).map((d:any)=>({...d,lead:l}))),[leads]);if(loading)return <div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-24 bg-white border border-[#E3E8EF] rounded-2xl animate-pulse"/>)}</div>;if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div>;return <div className="max-w-[1000px] mx-auto"><div className="mb-7"><p className="text-[11px] font-bold tracking-[3px] uppercase text-[#146BFF]">Documents</p><h1 className="text-[28px] font-extrabold tracking-tight mt-1">My Documents</h1><p className="text-[13px] text-[#8894A5] mt-1">Review document status for your active vehicle enquiries.</p></div>{rows.length===0?<div className="bg-white border border-[#E3E8EF] rounded-2xl p-7"><h2 className="font-extrabold">No documents requested</h2><p className="text-[13px] text-[#8894A5] mt-1">Required documents will appear here when your enquiry reaches the document stage.</p><Link href="/portal/enquiries" className="inline-flex mt-5 rounded-lg bg-[#146BFF] text-white px-5 py-2.5 text-[12.5px] font-semibold">View My Enquiries</Link></div>:<div className="space-y-3">{rows.map((d:any)=><Link key={`${d.lead.id}-${d.id}`} href={`/portal/leads/${d.lead.id}`} className="block bg-white border border-[#E3E8EF] rounded-2xl p-5 hover:border-[#146BFF]/40 transition-colors"><div className="flex items-start justify-between gap-4"><div><p className="font-extrabold text-[14px]">{d.type||d.name||'Document'}</p><p className="text-[12px] text-[#8894A5] mt-1">{d.lead.brand?.name} {d.lead.model?.name} · {d.lead.leadCode}</p></div><span className={`rounded-full px-3 py-1 text-[11px] font-semibold ${tone[d.status]||'bg-slate-500/10 text-slate-600'}`}>{status[d.status]||d.status||'Pending'}</span></div>{d.status==='REJECTED'&&d.rejectionReason&&<p className="mt-3 text-[12px] text-red-700">Reason: {d.rejectionReason}</p>}<p className="mt-4 text-[12px] font-semibold text-[#146BFF]">Open deal & document details →</p></Link>)}</div>}</div>}
